### ISSUE TITLE
Not support scalar result

### ISSUE THREAD

**Issue by bigperson** [rambler-digital-solutions/hydrogen#1]
- Hydrogen Version: (e.g. dev-master)
- PHP Version: (e.g. 7.2)

### Description:

I can not get scalar quantities except count.

### Steps To Reproduce:

```php
$this->query->select('SUM(field)')->get();
```
It is return collection, but not scalar

### What happens instead?
I use
```php
$query = $this->query->getQueryBuilder($this->query);
$alias = $query->getRootAliases()[0];

return $query
        ->select('SUM('.$alias.'.field) as sum')
        ->where($alias.'.user', 'user')
        ->getQuery()->getSingleScalarResult();
```
 For the solution, which is not very convenient.

**Comment by SerafimArts** [comment]
Implemented (https://github.com/rambler-digital-solutions/hydrogen/commit/69b436944d2ac497501a8a22ed935f5dd64b4ee2):
```php
$sum = $this->query->select('SUM(field) as sum`)->scalar('sum', 'int');
```
