### ISSUE TITLE
Add method next and prev from entity

### ISSUE THREAD

**Issue by chiqui3d** [rambler-digital-solutions/hydrogen#7]
- Hydrogen Version: (e.g. dev-master)
- PHP Version: (e.g. 7.1)

### Description:
It would be possible to add the methods "next" and "prev", based on a result of an entity, that way for example in a blog easily get the previous and next article, and the same for the next and prev meta tags.

thanks

**Comment by SerafimArts** [comment]
I understand that I want something like that?
```php
$result = $query->where('some', 23)->paginate(10);

var_dump($result->current()); // Article #1 
var_dump($result->prev()); // null
var_dump($result->next()); // Article #2 
```

**Comment by SerafimArts** [comment]
> SerafimArts closed this just now

Whoops, missclick)

**Comment by chiqui3d** [comment]
Well it would be better without paginate(although with paginate is another good option), so for example:

```
$post = $repository->query->where('id', 2)->get();
$post->prev();
$post->next();
```
I currently do the following, but I think that asking may not make sense.

```
public function next($blog){

        $nextBlog = $this->em->getRepository('App:Blog')->createQueryBuilder('b')
        ->where('b.id > :id')->setParameter('id', $blog->getId())
        ->getQuery()
        ->getOneOrNullResult();

        return $nextBlog;
    }
```

**Comment by SerafimArts** [comment]
The `get()` method returns an array and its signature cannot be changed. For collections, use the `collect()` method, this will greatly simplify working with iterators.

In addition, you can create your own method:
```php
$cursor = function (int $id, string $field = 'id'): object {
    // Just alias
    $query = $this;

    // Current query execution with "id = X" and "LIMIT 1"
    $result = $query->clone()->where($field, $id)->take(1)->first();

    return new class ($this, $result, $id, $field) {
        // $this->query->clone()->where($field, '>', $id)->asc($id)->first()
        public function next() { ... }

        // $this->query->clone()->where($field, '<', $id)->desc($id)->first()
        public function prev() { ... }
    }; 
};

Query::macro('cursor', $cursor);

//
// Execution
//
$blog = $query->where(...)->orderBy(...)->cursor($blog->getId());
```

**Comment by chiqui3d** [comment]
Very good idea, I understand the concept, but I use Symfony with no Laravel, anyway thank you very much. Also some idea of using it without macros ?

**Comment by SerafimArts** [comment]
> Very good idea, I understand the concept, but I use Symfony with no Laravel, anyway thank you very much

This example is framework-agnostic. On a Symfony, it will work the same way. The `macro()` support is implemented inside `Query` to expand its capabilities.

> Also some idea of using it without macros ?

Using scopes (https://github.com/rambler-digital-solutions/hydrogen#query-scopes) like this:

```php
interface CursorInterface
{
   public function current(): object;
   public function next(): ?object;
   public function prev(): ?object;
}

class MyRepository extends EntityRepository
{
    use Hydrogen;
    
    public function cursor(int $id): CursorInterface
    {
        $key = \array_first($this->getClassMetadata()->getIdentifier());

        $query = $this;

        $result = $query->clone()->where($key, $id)->take(1)->first();

        return new MyExampleCursor($query, $result, $id, $key);
    }
}


$cursor = $repository->cursor(42); // Scope method `cursor()` invocation

dump($cursor->current());
dump($cursor->next());
dump($cursor->prev());
```

It can be implemented as a trait, for example

**Comment by chiqui3d** [comment]
Perfect, I'll try and thank you very much for the help.
